name: DBNet
base: ['/content/drive/MyDrive/DBNet.pytorch-colab/config/icdar2015.yaml']
arch:
  type: Model
  backbone:
    type: MobileNetV3
    pretrained: false
  neck:
    type: FPN
    inner_channels: 256
  head:
    type: DBHead
    out_channels: 2
    k: 50
post_processing:
  type: SegDetectorRepresenter
  args:
    thresh: 0.3
    box_thresh: 0.7
    max_candidates: 1000
    unclip_ratio: 1.5 # from paper
metric:
  type: QuadMetric
  args:
    is_output_polygon: false
loss:
  type: DBLoss
  alpha: 1
  beta: 10
  ohem_ratio: 3
optimizer:
  type: Adam
  args:
    lr: 0.001
    weight_decay: 0
    amsgrad: true
lr_scheduler:
  type: WarmupPolyLR
  args:
    warmup_epoch: 3
trainer:
  seed: 2
  epochs: 100
  log_iter: 100
  show_images_iter: 50
  resume_checkpoint: '/content/drive/MyDrive/DBNet.pytorch-colab/output/DBNet_MobileNetV3_FPN_DBHead/checkpoint/model_best.pth'
  finetune_checkpoint: ''
  output_dir: output
  tensorboard: true
dataset:
  train:
    dataset:
      args:
        data_path:
          - /content/10k_dataset/train.txt
        img_mode: RGB
    loader:
      batch_size: 4
      shuffle: true
      pin_memory: true
      num_workers: 0
      collate_fn: ''
  validate:
    dataset:
      args:
        data_path:
          - /content/10k_dataset/test.txt
        pre_processes:
          - type: ResizeShortSize
            args:
              short_size: 736
              resize_text_polys: false
        img_mode: RGB
    loader:
      batch_size: 1
      shuffle: false
      pin_memory: false
      num_workers: 0
      collate_fn: ICDARCollectFN
